In [1]:
#Funciones transformar inputs en outputs

In [2]:
range(20,31)

range(20, 31)

In [3]:
list(range(20,31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [4]:
Milista = list(range(20,31))

In [5]:
print(Milista)
len(Milista)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


11

In [7]:
max(Milista), min(Milista)

(30, 20)

.....

In [8]:
L=[345,553,698,934,678,521]
L

[345, 553, 698, 934, 678, 521]

In [9]:
import numpy as np

In [10]:
np.array(L) #Convertir listas en arreglo

array([345, 553, 698, 934, 678, 521])

In [11]:
a = np.array(L)
a

array([345, 553, 698, 934, 678, 521])

In [12]:
L[1:]

[553, 698, 934, 678, 521]

In [14]:
L[0:2]

[345, 553]

In [15]:
L[::2]

[345, 698, 678]

In [16]:
a[2:] #Con los arreglos no se esta creando un nuevo array como si con las listas cuando se les hace slice

array([698, 934, 678, 521])

In [19]:
c = a.copy()

In [20]:
c

array([345, 553, 698, 934, 678, 521])

In [22]:
#Datos Tarea
ingresosMensuales = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
gastosMensuales = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]
   


In [29]:
UtilidadMensual = []

for i in range (0, len(ingresosMensuales)):
    UtilidadMensual.append(ingresosMensuales[i]-gastosMensuales[i])
UtilidadMensual

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [39]:
UtilidadMensualRedondeada = []

for i in range(0, len(UtilidadMensual)):
    UtilidadMensualRedondeada.append(round(UtilidadMensual[i]))
UtilidadMensualRedondeada
    

[2523, 1911, -3708, -2914, -600, 7265, 8211, 3945, 3328, -2239, 660, 11630]

In [42]:
UtilidadDespuesImpuestos = []

for i in range(0, len(UtilidadMensualRedondeada)):
    UtilidadDespuesImpuestos.append(round(0.7*UtilidadMensualRedondeada[i]))
    
UtilidadDespuesImpuestos
    

[1766, 1338, -2596, -2040, -420, 5086, 5748, 2762, 2330, -1567, 462, 8141]

In [46]:
MargenUtilidadMensual = []

for i in range(0, len(UtilidadDespuesImpuestos)):
    MargenUtilidadMensual.append( round((UtilidadDespuesImpuestos[i]/ingresosMensuales[i])*100))
MargenUtilidadMensual

[12, 18, -30, -22, -5, 63, 50, 28, 23, -11, 4, 53]

In [75]:
PromedioUDIMensual = round(sum(UtilidadDespuesImpuestos)/len(UtilidadDespuesImpuestos))
                      
#Creacion listado de comentarios 
ComentariosporMes = []
#Evaluación de condicion de Buen Mes o Mal mes y agregación de elementos al listado con funcion append
for i in range(0,len(UtilidadDespuesImpuestos)):
    if UtilidadDespuesImpuestos[i] > PromedioUDIMensual :
            ComentariosporMes.append("Buen Mes")
    if UtilidadDespuesImpuestos[i] < PromedioUDIMensual:
                ComentariosporMes.append("Mal Mes")

#Evaluación de Mejor y Peor mes y reemplazo en en listado de comentarios por mes sin crear un nuevos elementos en lista
for i in range(0,len(UtilidadDespuesImpuestos)):
    if UtilidadDespuesImpuestos[i] == max(UtilidadDespuesImpuestos):
        ComentariosporMes[i]="Mejor Mes"
    if UtilidadDespuesImpuestos[i] == min(UtilidadDespuesImpuestos):
            ComentariosporMes[i]="Peor Mes"
            
print(PromedioUDIMensual)
ComentariosporMes


           

1751


['Buen Mes',
 'Mal Mes',
 'Peor Mes',
 'Mal Mes',
 'Mal Mes',
 'Buen Mes',
 'Buen Mes',
 'Buen Mes',
 'Buen Mes',
 'Mal Mes',
 'Mal Mes',
 'Mejor Mes']

In [70]:
print("Ingresos:")
print(ingresosMensuales)
print("Gastos:")
print(gastosMensuales)
print("UtilidadMensual: ")
print(UtilidadMensualRedondeada)
print("Utilidad despues de Impuestos:")
print(UtilidadDespuesImpuestos)
print("MargenUtilidad: ")
print(MargenUtilidadMensual)
print("Comentarios frente a los meses:")
print(ComentariosporMes)


Ingresos:
[14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.5]
Gastos:
[12051.82, 5695.07, 12319.2, 12089.72, 8658.57, 840.2, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]
UtilidadMensual: 
[2523, 1911, -3708, -2914, -600, 7265, 8211, 3945, 3328, -2239, 660, 11630]
Utilidad despues de Impuestos:
[1766, 1338, -2596, -2040, -420, 5086, 5748, 2762, 2330, -1567, 462, 8141]
MargenUtilidad: 
[12, 18, -30, -22, -5, 63, 50, 28, 23, -11, 4, 53]
Comentarios frente a los meses:
['Buen Mes', 'Mal Mes', 'Peor Mes', 'Mal Mes', 'Mal Mes', 'Buen Mes', 'Buen Mes', 'Buen Mes', 'Buen Mes', 'Mal Mes', 'Mal Mes', 'Mejor Mes']


range(0, 1)